version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: autoclave-db
    environment:
      POSTGRES_DB: autoclave
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Python Backend Services (Sensor + API)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: autoclave-backend
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=autoclave
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - COM_PORT=/dev/ttyACM0  # USB serial device
      - BAUD_RATE=9600
      - SLAVE_ID=1
    volumes:
      - /dev/ttyACM0:/dev/ttyACM0  # USB serial device
    privileged: true  # Required for serial device access
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_BASE_URL=http://localhost:5000
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    container_name: autoclave-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    name: autoclave-network

